[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ipd"
version = "0.1"
dependencies = [
    'hydra-core',
    'hypothesis',
    'icecream',
    'requests',
    'pydantic',
    'numpy',
    'assertpy',
    'eliot',
    'eliot-tree',
]
requires-python = ">=3.10"
