name: 📖 Documentation Improvement
description: Suggest improvements or additions to documentation
title: "[Docs] "
labels: [documentation]
assignees: ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be documented or improved?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: If applicable, provide example code snippets or references.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details?
