"""add user/group

Revision ID: 1edcda2060b8
Revises: 7e64bd2154f1
Create Date: 2024-10-07 22:05:34.546323

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edcda2060b8'
down_revision: Union[str, None] = '7e64bd2154f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbgroup',
    sa.Column('ispublic', sa.Boolean(), nullable=False),
    sa.Column('telemetry', sa.Boolean(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbuser',
    sa.Column('ispublic', sa.Boolean(), nullable=False),
    sa.Column('telemetry', sa.Boolean(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbusergrouplink',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupid'], ['dbgroup.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['dbuser.id'], ),
    sa.PrimaryKeyConstraint('userid', 'groupid')
    )
    op.create_table('dbuseruserlink',
    sa.Column('followerid', sa.Integer(), nullable=False),
    sa.Column('followingid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followerid'], ['dbuser.id'], ),
    sa.ForeignKeyConstraint(['followingid'], ['dbuser.id'], ),
    sa.PrimaryKeyConstraint('followerid', 'followingid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbuseruserlink')
    op.drop_table('dbusergrouplink')
    op.drop_table('dbuser')
    op.drop_table('dbgroup')
    # ### end Alembic commands ###
