"""fix some id names

Revision ID: 597003c7fcc8
Revises: 1edcda2060b8
Create Date: 2024-10-08 00:08:02.501401

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597003c7fcc8'
down_revision: Union[str, None] = '1edcda2060b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbpoll', 'workflowname')
    op.add_column('dbreview', sa.Column('workflowid', sa.Integer(), nullable=False))
    op.drop_constraint('dbreview_workflowbbkey_fkey', 'dbreview', type_='foreignkey')
    op.create_foreign_key(None, 'dbreview', 'dbworkflow', ['workflowid'], ['id'])
    op.drop_column('dbreview', 'workflowbbkey')
    op.drop_column('dbreview', 'filecontent')
    op.drop_column('dbreview', 'flowstepname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbreview', sa.Column('flowstepname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('dbreview', sa.Column('filecontent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dbreview', sa.Column('workflowbbkey', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dbreview', type_='foreignkey')
    op.create_foreign_key('dbreview_workflowbbkey_fkey', 'dbreview', 'dbworkflow', ['workflowbbkey'], ['id'])
    op.drop_column('dbreview', 'workflowid')
    op.add_column('dbpoll', sa.Column('workflowname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
