name: run pytest on digs with slurm
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: run ruff
      run: |
        /home/bench/.local/bin/ruff check 2>&1 | tee ruff.log

    - name: run pytest digs
      run: |
        srun -p gpu --gres=gpu:a4000:1 --cpus-per-task=4 --mem=32G apptainer exec /home/sheffler/project/apptainer/TEST pytest 2>&1 | tee pytest.log

    - name: check test results
      run: |
        python ipd/tests/check_test_results.py

    # - name: build docs
    #   run: |
    #     export LC_ALL=C
    #     cd doc
    #     rm -rf source/api
    #     export PYTHON=../rf_diffusion/exec/bakerlab_rf_diffusion_aa.sif
    #     export PYTHONPATH=..:../rf_diffusion:../rf2aa:../lib/rf2aa/rf2aa/SE3Transformer
    #     $PYTHON -m sphinx.ext.apidoc -o source/api ../rf_diffusion
    #     $PYTHON -m sphinx.ext.apidoc -o source/api ../rf2aa
    #     $PYTHON -m sphinx.cmd.build -M html source build
    #     prnum=$(git branch | cut -b 26-28)
    #     mkdir -p $HOME/public/rf_diffusion/$prnum/
    #     rsync -a build/html/ $HOME/public/rf_diffusion/$prnum/
