name: run pytest on digs with slurm
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: setup
      run: |
        ipd update
        ipd ci update_library ipd

    - name: run ruff
      run: |
        ipd ci tests ruff ipd

    - name: validate pyproject
      run: |
        validate-pyproject pyproject.toml

    - name: run pyright
      run: |
        export PYTHONPATH=/home/bench/.conda/envs/ci/lib/python3.12/site-packages
        /home/bench/.conda/envs/ci/bin/pyright -p pyproject.toml

    - name: run pytest digs
      run: |
        ipd ci tests pytest

    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://cli.codecov.io/latest/linux/codecov && chmod +x codecov
        ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml

    - name: check test results
      run: |
        ipd ci tests check

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # - name: build docs
    #   run: |
    #     export LC_ALL=C
    #     cd doc
    #     rm -rf source/api
    #     export PYTHON=../rf_diffusion/exec/bakerlab_rf_diffusion_aa.sif
    #     export PYTHONPATH=..:../rf_diffusion:../rf2aa:../lib/rf2aa/rf2aa/SE3Transformer
    #     $PYTHON -m sphinx.ext.apidoc -o source/api ../rf_diffusion
    #     $PYTHON -m sphinx.ext.apidoc -o source/api ../rf2aa
    #     $PYTHON -m sphinx.cmd.build -M html source build
    #     prnum=$(git branch | cut -b 26-28)
    #     mkdir -p $HOME/public/rf_diffusion/$prnum/
    #     rsync -a build/html/ $HOME/public/rf_diffusion/$prnum/
